language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "m5WsEXZKSwx9sH4+Eynp5fS0WMzFbWGvwmziotmhGGP16bYwsHNkeYZY9tmKl4XWxXEcpvdpt1Pq8NIGskM+VJ2jTClWdgnl5RuLt8tcRbwaGYBp4J4OVbpkT7LHxKUspCgG+krJic1JcCNCgMT7VU+4hc5u0kJ9uo/DaZrzd84="
script:
  - npm run travis
after_success:
  - $(npm bin)/coveralls < ./coverage/lcov.info
